server {
    listen 80;
    client_max_body_size 200M;

    location /api/ {
        proxy_pass https://tzb-app.fly.dev/api/;
        proxy_set_header Host tzb-app.fly.dev;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 300s;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}

